#!/bin/bash

printf "" > tmp

if [[ $1 = --debug-installer ]]; then
    while [ 1 = 1 ]; do
        read -p "Input Bash Command" input
        if [[ "$input" = "exit" ]]; then
            break
        fi
        $input
    done
    exit
fi

if [[ "$1" = "--help" || "$2" = "--help" || "$3" = "--help" ]]; then
    echo --help >> tmp
fi
printf "\n" >> tmp

if [[ "$1" = "-d" || "$2" = "-d" || "$3" = "-d" ]]; then
    echo -d >> tmp
fi
printf "\n" >> tmp

if [[ "$1" = "-s" || "$2" = "-s" || "$3" = "-s" ]]; then
    echo "-s" >> tmp
fi
printf "\n" >> tmp

if [[ "$1" = "-u" || "$2" = "-u" || "$3" = "-u" ]]; then
    echo "-u" >> tmp
fi
printf "\n" >> tmp

if [[ "$1" = "-r" || "$2" = "-r" || "$3" = "-r" ]]; then
    echo "-r" >> tmp
fi
printf "\n" >> tmp

g++ ./src/install.cpp -o ./install.out

if [[ "$1" = "wait" ]]; then
    read null
fi
./install.out
exit